name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  push-to-gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "yoonc01"
          git config user.email "yoonc01@hotmail.com"

      - name: Remove .github directory and README
        run: |
          rm -rf .github
          rm -rf README.md
          git add -A
          git commit -m "Remove .github and README before pushing to GitLab" || echo "No changes to commit"

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@lab.ssafy.com/yoonc01/homework.git
          git remote -v

      - name: Pull from GitLab to avoid conflicts
        run: |
          git fetch gitlab
          git merge gitlab/master || echo "Merge conflict detected, resolving automatically"
          git add -A
          git commit -m "Resolve merge conflicts automatically" || echo "No conflicts to resolve"

      - name: Push to GitLab
        run: |
          git push gitlab main:master
